### ISSUE TITLE
[Bug] Location is loading, please wait...

### ISSUE THREAD

**Issue by pablo03v** [MindsHub/insigno_frontend#6]
Whenever I open the app it says that the location is loading, but nothing happens even after minutes

**Comment by Stypox** [comment]
This is because the GPS is being used instead of the fused location provider. We had to make this choice because the fused provider, which uses all of gps, wifi, bluetooth and mobile network to find the location, is only available on devices with Google Play Services (which is shameful of Google). But publishing the app on F-Droid requires not to impose any dependency on Google Play Services, since a dependency on proprietary software would imply that the app would not be free software anymore. Could you test if other maps apps published on F-Droid expose the same problem? You may try [this one](https://f-droid.org/en/packages/net.osmand.plus/), for example.

**Comment by pablo03v** [comment]
haha, the title. Yeah, I am on calyxOS I know the struggle. 

I use organic maps on a regular basis and didn't have a problem yet.

Is this enough information or should I also try OSMand? I just didn't use that yet as it doesn't look as beautiful imo

**Comment by Stypox** [comment]
Thanks for the feedback, there's no need to try OSMand if you use Organic Maps from F-Droid, since they also have to workaround the Play Services limitation. I will look into how they are doing it and test it out on my phone (which also doesn't have Play Services and is sometimes slow at loading the location).

**Comment by Stypox** [comment]
@pabloscloud [Their strategy](https://github.com/organicmaps/organicmaps/blob/master/android/src/app/organicmaps/location/AndroidNativeProvider.java) is to try all available providers (i.e. fused, GPS and network). What Insigno did was to just use the GPS provider, since it seemed like the fused one, which would be chosen by Android's filters, did not work. It turns out fused did not work on my phone because of LineageOS problems, but on other phones it might work better than just GPS. I now implemented OrganicMaps' strategy in Insigno, could you test if this APK works better for you? [app-release.zip](https://github.com/MindsHub/insigno_frontend/files/11420073/app-release.zip) (it has a different package name, `org.mindshub.insigno_testing`)

**Comment by pablo03v** [comment]
I will. And also I noticed that it works outside of a building. I'll test if it's more accurate tho

**Comment by Stypox** [comment]
I asked other people to test and everyone experienced better location updates, even inside of buildings, and with faster loading times. This is probably because "fused" is being used there.

**Comment by pablo03v** [comment]
Nice, I need to implement this in my own project too then

**Comment by WAPEETY** [comment]
Hi I have the same problem,
I downloaded the test version linked in this thread and it works
